FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

RUN python3 init_db.py

CMD ["flask", "--app", "api", "run", "--host", "0.0.0.0"]
